global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "megalodon-core"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["megalodon-api:8000", "megalodon-gateway:8080"]
